version: '2'
services:
  reactmaps:
    build:
      context: ./
    command: npm start
    env_file: ./.env
    environment: 
      - NODE_ENV=production
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules/
    ports:
      - "3000:3000"
    stdin_open: true
